<?php
namespace AtomPie\Gui\Component {

    class AutoGeneratedName
    {

        private $sName;
        private static $aNumbers;

        public function __construct($sName)
        {
            $this->sName = $sName;
            if (!isset(self::$aNumbers[$sName])) {
                self::$aNumbers[$sName] = 0;
            }
            ++self::$aNumbers[$sName];
        }

        public function __toString()
        {
            return $this->sName . self::$aNumbers[$this->sName];
        }

    }

}