<?php
namespace AtomPie\Gui {

    use AtomPie\Boundary\Gui\Component\IHaveContext;
    use AtomPie\Gui\Component\AutoGeneratedName;
    use AtomPie\Gui\Component\Context;
    use AtomPie\Gui\Component\Part;

    abstract class Component extends Part
    {

        /**
         * @param string $sName
         * @param IHaveContext $oContext
         */
        public function __construct($sName = null, IHaveContext $oContext = null)
        {

            if ($sName === null) {
                $sName = new AutoGeneratedName($this->getType()->getName());
            }

            if ($oContext === null) {
                $oContext = new Context();
            }

            parent::__construct($sName, $oContext);

        }

    }

}
